<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'menu_name' => 'Dashboard',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '0',
                'menu_order' => '1',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/dashboard',
                'icon' => 'grid'
            ],
            [
                'menu_name' => 'Dealer',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '2',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'user'
            ],
            [
                'menu_name' => 'Dealer List',
                'group_name' => null,
                'parent_id' => '2',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '3',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/dealerlist',
                'icon' => null
            ],
            [
                'menu_name' => 'Retailer',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '4',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'user'
            ],
            [
                'menu_name' => 'Retailer List',
                'group_name' => null,
                'parent_id' => '4',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '5',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/retailerlist',
                'icon' => null
            ],
            [
                'menu_name' => 'Orders',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '6',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'file-text'
            ],
            [
                'menu_name' => 'Orders',
                'group_name' => null,
                'parent_id' => '6',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '7',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/order',
                'icon' => null
            ],
            [
                'menu_name' => 'Approved Orders',
                'group_name' => null,
                'parent_id' => '6',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '8',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/approvedorder',
                'icon' => null
            ],
            [
                'menu_name' => 'Dis-Approved Orders',
                'group_name' => null,
                'parent_id' => '6',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '9',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/disapprovedorder',
                'icon' => null
            ],
            [
                'menu_name' => 'Shipment',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '10',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'truck'
            ],
            [
                'menu_name' => 'Shipment',
                'group_name' => null,
                'parent_id' => '10',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '11',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/shipment',
                'icon' => null
            ],
            [
                'menu_name' => 'Team',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '12',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'users'
            ],
            [
                'menu_name' => 'Team',
                'group_name' => null,
                'parent_id' => '12',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '13',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/team',
                'icon' => null
            ],
            [
                'menu_name' => 'Costing',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '14',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'dollar-sign'
            ],
            [
                'menu_name' => 'Costing',
                'group_name' => null,
                'parent_id' => '14',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '15',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/costing',
                'icon' => null
            ],
            [
                'menu_name' => 'Projects & Timeline',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '16',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'folder'
            ],
            [
                'menu_name' => 'Projects & Timeline',
                'group_name' => null,
                'parent_id' => '16',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '17',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/projecttimeline',
                'icon' => null
            ],
            [
                'menu_name' => 'Invoices',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '18',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'folder'
            ],
            [
                'menu_name' => 'Invoices',
                'group_name' => null,
                'parent_id' => '18',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '19',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/invoice',
                'icon' => null
            ],
            [
                'menu_name' => 'Notifications',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '20',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'bell'
            ],
            [
                'menu_name' => 'Notifications',
                'group_name' => null,
                'parent_id' => '20',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '21',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/notification',
                'icon' => null
            ],
            [
                'menu_name' => 'Masters',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '22',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'aperture'
            ],
            [
                'menu_name' => 'Project',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '23',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/project',
                'icon' => null
            ],
            [
                'menu_name' => 'Category',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '24',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/category',
                'icon' => null
            ],
            [
                'menu_name' => 'Sub Category',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '25',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/subcategory',
                'icon' => null
            ],
            [
                'menu_name' => 'Zone',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '26',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/zone',
                'icon' => null
            ],
            [
                'menu_name' => 'Collections',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '27',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/collections',
                'icon' => null
            ],
            [
                'menu_name' => 'Sub Collections',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '28',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/subcollections',
                'icon' => null
            ],
            [
                'menu_name' => 'Banner',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '29',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/banner',
                'icon' => null
            ],
            [
                'menu_name' => 'Metal Type',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '30',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/metaltype',
                'icon' => null
            ],
            [
                'menu_name' => 'Brand',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '31',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/brand',
                'icon' => null
            ],
            [
                'menu_name' => 'Shape',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '32',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/shape',
                'icon' => null
            ],
            [
                'menu_name' => 'Weight',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '33',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/weight',
                'icon' => null
            ],
            [
                'menu_name' => 'Plating',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '34',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/plating',
                'icon' => null
            ],
            [
                'menu_name' => 'Size',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '35',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/size',
                'icon' => null
            ],
            [
                'menu_name' => 'Color',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '36',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/color',
                'icon' => null
            ],
            [
                'menu_name' => 'Jewel Type',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '37',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/jeweltype',
                'icon' => null
            ],
            [
                'menu_name' => 'Finish',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '38',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/finish',
                'icon' => null
            ],
            [
                'menu_name' => 'Style',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '39',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/style',
                'icon' => null
            ],
            [
                'menu_name' => 'Popup',
                'group_name' => null,
                'parent_id' => '22',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '40',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/popup',
                'icon' => null
            ],
            [
                'menu_name' => 'Products',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '41',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'gift'
            ],
            [
                'menu_name' => 'Add Product',
                'group_name' => null,
                'parent_id' => '41',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '42',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/product',
                'icon' => null
            ],
            [
                'menu_name' => 'Product List',
                'group_name' => null,
                'parent_id' => '41',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '43',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/productlist',
                'icon' => null
            ],
            [
                'menu_name' => 'Roles & Permission',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '1',
                'menu_order' => '44',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'lock'
            ],
            [
                'menu_name' => 'Roles',
                'group_name' => null,
                'parent_id' => '44',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '45',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/role',
                'icon' => null
            ],
            [
                'menu_name' => 'Menu Permission',
                'group_name' => null,
                'parent_id' => '44',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '46',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/rolepermission',
                'icon' => null
            ],
            [
                'menu_name' => 'Users',
                'group_name' => null,
                'parent_id' => '44',
                'is_mainmenu' => '0',
                'is_module' => '0',
                'menu_order' => '47',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/users',
                'icon' => null
            ],
            [
                'menu_name' => 'Help & Center',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '0',
                'menu_order' => '48',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'help-circle'
            ],
            [
                'menu_name' => 'Settings',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '0',
                'menu_order' => '49',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/settings',
                'icon' => 'settings'
            ],
            [
                'menu_name' => 'Stock Maintenance',
                'group_name' => null,
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '0',
                'menu_order' => '50',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/stockmaintenance',
                'icon' => 'layers'
            ],
            [
                'menu_name' => 'Dashboard',
                'group_name' => 'Dealer',
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '0',
                'menu_order' => '51',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/dealer_dashboard',
                'icon' => 'grid'
            ],
            [
                'menu_name' => 'Orders',
                'group_name' => 'Dealer',
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '0',
                'menu_order' => '52',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => '/order_details',
                'icon' => 'file-text'
            ],
            [
                'menu_name' => 'Shipment',
                'group_name' => 'Dealer',
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '0',
                'menu_order' => '53',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'truck'
            ],
            [
                'menu_name' => 'Ready Stock',
                'group_name' => 'Dealer',
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '0',
                'menu_order' => '54',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'archive'
            ],
            [
                'menu_name' => 'Help & Center',
                'group_name' => 'Dealer',
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '0',
                'menu_order' => '55',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'help-circle'
            ],
            [
                'menu_name' => 'Settings',
                'group_name' => 'Dealer',
                'parent_id' => '0',
                'is_mainmenu' => '1',
                'is_module' => '0',
                'menu_order' => '56',
                'is_visible' => '1',
                'show_superadmin' => '1',
                'menu_url' => null,
                'icon' => 'settings'
            ]
        ];

        Menu::Insert($data);
    }
}
